version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: marshmallow
    versions:
    - 3.11.0
  - dependency-name: responses
    versions:
    - 0.13.1
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: flaskoidc
    versions:
    - 0.2.1
  - dependency-name: mypy
    versions:
    - "0.800"
    - "0.812"
  - dependency-name: pytest-cov
    versions:
    - 2.11.1
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
- package-ecosystem: npm
  directory: "/amundsen_application/static"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: terser-webpack-plugin
    versions:
    - 4.2.3
  - dependency-name: "@babel/plugin-proposal-export-namespace-from"
    versions:
    - 7.12.13
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
  - dependency-name: node-sass
    versions:
    - 5.0.0
  - dependency-name: react-avatar
    versions:
    - 3.10.0
  - dependency-name: core-js
    versions:
    - 3.9.1
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.15
    - 6.1.18
    - 6.1.21
  - dependency-name: "@types/webpack"
    versions:
    - 4.41.26
  - dependency-name: postcss
    versions:
    - 8.2.7
  - dependency-name: urijs
    versions:
    - 1.19.4
    - 1.19.6
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: nested-object-assign
    versions:
    - 1.0.4
  - dependency-name: sanitize-html
    versions:
    - 1.27.5
  - dependency-name: "@storybook/addon-info"
    versions:
    - 5.3.21
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.3.0
  - dependency-name: jest
    versions:
    - 26.6.3
  - dependency-name: webpack-sources
    versions:
    - 2.2.0
  - dependency-name: axios
    versions:
    - 0.21.1
